### ISSUE TITLE
Engine files in Default Uncontrolled Changelist

### ISSUE THREAD

**Issue by DinoLampa** [ProjectBorealis/UE4GitPlugin#167]
Hi,

Thanks for your great plugin.

We're having an issue where many engine assets are flagged to be reconciled by the editor.
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/171628524/b7f49f2a-a6ca-40fa-9432-452f8ef3081d)

These are engine files not synced with our repo (nor do we want them to), you can see the result of the reconcile in the picture attached. 

![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/171628524/5235d914-c2d1-45a5-a162-f6a958f59446)

Moreover the revert function doesn't unlock any of the modified assets: checking out assets from the editor works fine (and they appear locked when running _git lfs locks_) but when reverted they remain checked out until they are pushed or unlocked via command line.

*files after revert still checked out
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/171628524/70d93760-98a2-4e42-b5c1-173861f03f9b)

Our current setup: the project is foreign to the engine,  we're using the 3.16 version of the plugin, which we recompiled for the latest version of the engine 5.4.2; we tried installing the plugin in the project directory as well as the engine folder, to no avail. We tried replacing the git-lfs.exe with the latest available, but it seems incompatible with flags used by the plugin:
![image](https://github.com/ProjectBorealis/UEGitPlugin/assets/171628524/e05c735f-a0a0-4589-8f11-52875f81ae48)

Our source control works fine from command line, we are able to lock/unlock files and push binaries to the lfs storage.
This is our .gitattributes:

```
*.bat eol=crlf
*.sh eol=lf

[attr]lock filter=lfs diff=lfs merge=binary -text lockable
[attr]lockonly lockable
[attr]lfs filter=lfs diff=lfs merge=binary -text
[attr]lfstext filter=lfs diff=lfstext merge=lfstext -text

# Unreal Engine file types.
*.uasset lock
*.umap lock
*.locres lfs
*.locmeta lfs
# Steam Audio files
*.phononscene lfs
*.probebox lfs
*.probebatch lfs
*.bakedsources lfs
# Binaries
*.exe lfs
*.dll lfs
*.pdb lfs
*.rcc lfs
# FMOD
*.bank lfs
*.wav lfs
*.mp3 lfs
*.ogg lfs
*.flac lfs
# Icons
*.png lfs
*.ico lfs
*.icns lfs
*.jpg lfs
# Movies
*.bk2 lfs

*.fbx lfs
*.3ds lfs
*.psd lfs
*.xcf lfs
```

Thanks again for your work.

**Comment by mastercoms** [comment]
Hi! The first issue with the engine files is definitely a bug. As for the second one about locking/unlocking: did you set your LFS username correctly?

**Comment by DinoLampa** [comment]
Hi

Sorry for the late reply.

For the first issue, reproduction steps were simply running the project with vanilla UE 5.4.2, from the very first setup of the plugin all the engine files were flagged to be reconciled. Also on one occasion during the reconcile all the interested files were lost, and we had to repair the engine through the Epic Launcher, unfortunately there was no crash dump.

As for the second issue, we fixed the LFS username and now it seems to work fine.

Thanks for the help.

**Comment by mastercoms** [comment]
Could you test the latest dev branch to see if it resolves the issue?

**Comment by tavik000** [comment]
Hi @mastercoms 
I have the same issue. Recently I upgraded my project from UE5.5 to 5.6

I ran into an issue where I couldn't commit the LI_Light (a Level Instance that includes the Skybox) actor.
The submission failed, as shown at 2:05 in the video:
https://youtu.be/AB2FArMXnBQ?si=FZwc67im9lZG9zYs&t=125
I checked the log and saw error messages (around 4:46 in the video).

![Image](https://github.com/user-attachments/assets/1b753c58-ec46-4776-b141-c3e3023f74f1)

It turns out the Skybox actor is using WorldGridMaterial, which is Engine content and not tracked by Git.
So I figured out I needed to copy the material and its related assets into my project folder.

So I copied the material and related textures from the Engine content into my project. and use the copied material for that Skybox actor.

After doing that, I encountered a new issue: when I click Revision Control → View Changes, I get Git error messages, and around 7,000 Engine content files appear in the Uncontrolled Changelists. As a result, I'm unable to submit anything.

maybe was I touched the engine content that dirtied 7k files?

![Image](https://github.com/user-attachments/assets/61a73224-83d9-497c-bcb0-54040c1b9245)

![Image](https://github.com/user-attachments/assets/0edeeb24-6e98-4dd5-8cbb-e60ec9d4fd4e)

![Image](https://github.com/user-attachments/assets/cf28b22e-858a-41f9-982c-49ecd64b15bc)

I have a video recording that shows exactly when the error happens:
The moment the 7,000 files appear in Uncontrolled Changelists:
https://youtu.be/AB2FArMXnBQ?si=HwAr1AUBQrbDT_RB&t=1945

And now I cannot submit anything from editor because of the error. I am thinking of reinstall UE

**Comment by mastercoms** [comment]
Hm, that's very strange. It should be filtering out those engine files. Unfortunately we are still on 5.4 and we'll be upgrading to the latest version later, so it will take some time for us to debug these errors. Thank you though for the detailed information, it will help a lot!

Maybe reinstalling UE will work, but I don't really know what's causing the issue at this time so I don't have any suggestions. Sorry, I wish I could be of more help.

**Comment by tavik000** [comment]
@mastercoms 

Thanks for your reply.


I reinstalled UE5.6 to the same path, but the 7,000 files in the Uncontrolled Changelists were still there.  
Then, I downgraded my project back to UE5.5, but the Uncontrolled Changelists still showed 7,000 files.

I noticed it was still tracking files from the UE5.6 Engine folder, so I decided to uninstall UE5.6 and keep using UE5.5.  
After that, the Uncontrolled Changelists dropped to 0.

However, when I tried submitting anything, it started tracking UE5.5 Engine files, and I couldn’t submit.  
I tried deleting the Blockout Tools plugin and a Blueprint file that referenced the Engine files.  
But when submitting the deleted files, I got an error saying more 5.5 Engine files were being tracked.



**In short, here’s what I did:**

- Reinstalled UE5.6 → Didn't work  
- Downgraded to UE5.5 → Still tracked UE5.6 Engine files  
- Uninstalled UE5.6 → Uncontrolled Changelists dropped to 0  
- Tried submitting anything → Error: Cannot find directory path for UE5.5 Engine files  
- Deleted Blockout Plugin and a Blueprint that referenced Engine files  
- Tried submitting again → Error: Cannot find directory path for MORE UE5.5 Engine files  

I have a full devlog video recording every step I took.
https://www.youtube.com/watch?v=aOTwR6iUb7g

Section:

0:00:00 #1. Reinstall UE5.6
0:20:56 #2. Reinstall UE5.6 does not work, Uncontrolled Changelist remains 7k Engine files
0:23:15 #3. Downgrade the project back to UE5.5
0:29:48 #4. Uncontrolled Changelist still tracking UE5.6 files
0:30:09 #5. Delete UE5.6 and keep using UE5.5
0:44:52 #6. Test submit anything, now Uncontrolled Changelist is tracking UE5.5 engine files
0:46:25 #7. Try deleting a Blockout Tools Plugin and a Blueprint file that refers to that engine file
1:03:59 #8. Submitting deleted files, but now it tracks more engine files.
1:06:37 #9. Summary

**Comment by tavik000** [comment]
## Submission Issues and Workarounds

I figured out that there were two issues of my last reply↑:

1. **Uncontrolled changelists**  
2. **Unable to submit via the default method**

### Issue 1: Uncontrolled Changelists

The uncontrolled changelist does **not** affect the submission process.  
I can hide it by changing the project settings:  
Uncheck **"Enable Uncontrolled Changelists"**.

![Uncontrolled Changelist Setting](https://github.com/user-attachments/assets/564c24b9-7c7f-46ba-b2ae-048ac1346efe)

---

### Issue 2: Cannot Submit from "View Changes"

When I submit from **"View Changes"**, by right-clicking and selecting **"Submit Changelist"**, I get an error saying the Unreal Engine file cannot be found.

![Submission Error](https://github.com/user-attachments/assets/d308f9e4-4aa7-4e8f-8d87-4aad6702cebd)  
![Submission Error](https://github.com/user-attachments/assets/38f34ce3-c2d9-4e42-9763-250177216ece)

---

### Workaround: Submit from Asset Directly

But If I go to the asset’s location in the Content Browser, right-click, and choose **"Check In"**, the submission works successfully.

![Successful Submission](https://github.com/user-attachments/assets/1446b4b1-554e-4c8c-ae4b-5d95dda2528c)


So the submission is fine. Hope this also helps others.

**Comment by mastercoms** [comment]
This makes  it a lot more clear! So the error in issue 2 is preventing you from submitting?

**Comment by tavik000** [comment]
Yes, the error in issue 2 is preventing submission.

**Comment by BenjaminDo** [comment]
Looks like I have the same issue.

But When I hide the uncontrolled changelist (Issue 1) I get a new error when trying to submit the changelist
```
SourceControl: Error: Operation 'EditChangelist' not supported by revision control provider 'Git LFS 2'
SourceControl: Error: Failed to update changelist description.
```
